### ISSUE TITLE
关于批量生成的一些问题

### ISSUE THREAD

**Issue by w854155226** [spiritLHLS/docker#1]
限制硬盘   列出批量生成的信息

**Comment by spiritLHLS** [comment]
暂时研究到的情况中，除非使用cgroup对每个容器进行一对一限制，否则无法限制硬盘大小，原生的docker想要限制硬盘对宿主鸡的要求很苛刻，所以不做判断和适配

欢迎提供你的思路

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/docker/commit/f91a1d06192d215a6deaaa257f0a4ca4d05a49c9

修改了说明
