### ISSUE TITLE
docker安装window2019，远程连接不了

### ISSUE THREAD

**Issue by linlxh** [spiritLHLS/docker#2]
这个镜像是不是默认没开远程啊，端口我都开了，安装也没报错

**Comment by linlxh** [comment]
https://tc.886811.xyz/file/58c7295d8258ae78ccb4c.png

**Comment by spiritLHLS** [comment]
如果要排查错误，执行以下命令看看就知道有没有启动win成功了

```
dockr exec -it windows2019 bash -c "vagrant rdp"
```

如果输出不出现端口什么的，就是没启动成功

**Comment by linlxh** [comment]
![image](https://github.com/spiritLHLS/docker/assets/81435764/37f14da4-730d-445c-852c-161f2ad27087)
v1版cgroup启动咋看

**Comment by linlxh** [comment]
我是Centos安装的

**Comment by spiritLHLS** [comment]
> ![image](https://user-images.githubusercontent.com/81435764/261004176-1502ad45-7765-4dd2-b74b-282c40b3ca95.png)

这个就是没启动成功，安装过程中肯定有报错

**Comment by linlxh** [comment]
![image](https://github.com/spiritLHLS/docker/assets/81435764/50454de8-214e-43a7-a939-f5fdc6530268)

**Comment by spiritLHLS** [comment]
> ![image](https://user-images.githubusercontent.com/81435764/261004713-50454de8-214e-43a7-a939-f5fdc6530268.png)

确实报错了，但看不到啥造成的，你删了容器后执行

```
./onewindows.sh 2019 13389 Y | tee -a log
```

挂在screen里，最后创建成功在外面执行

```
cat log
```

看看最后的报错是啥我就知道啥情况了，初步怀疑是openssl出问题了

**Comment by linlxh** [comment]
好，我再试试

**Comment by spiritLHLS** [comment]
怎么样？

> 好，我再试试

**Comment by spiritLHLS** [comment]
如果有问题再大概本问题吧，暂时关闭
