### ISSUE TITLE
docker进程守护

### ISSUE THREAD

**Issue by srs81557877** [spiritLHLS/docker#7]
docker没有守护进程SSH未启动

**Comment by spiritLHLS** [comment]
https://www.spiritlhl.net/guide/docker/docker_build.html#%E5%AE%BF%E4%B8%BB%E6%9C%BA%E9%87%8D%E5%90%AF%E5%90%8E%E9%87%8D%E5%90%AF%E6%89%80%E6%9C%89%E5%AE%B9%E5%99%A8

目前还没有做docker容器的自修补程序，暂时先用这个方法解决先
